openapi: 3.0.1
info:
  title: Restapi
  description: API Definition of Restapi
  version: 1.0.0
servers:
- url: http://localhost:8290/restapi
paths:
  /getItems:
    get:
      parameters:
      - name: itemId
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
